// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdg_lekyn536z20INbAXylT5IHCkuccs0',
    appId: '1:930675311111:web:9af5958ec23e671c26e0a2',
    messagingSenderId: '930675311111',
    projectId: 'remouteconfigtest',
    authDomain: 'remouteconfigtest.firebaseapp.com',
    storageBucket: 'remouteconfigtest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAmHTKwj56Wx36vnLeOcyWEoMYY18DZV4',
    appId: '1:930675311111:android:899df9fd54a4aae026e0a2',
    messagingSenderId: '930675311111',
    projectId: 'remouteconfigtest',
    storageBucket: 'remouteconfigtest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1YZR3Q6e35kdUb-jBgviw4ykeFFFDaXA',
    appId: '1:930675311111:ios:1443c4bbc95c7c0026e0a2',
    messagingSenderId: '930675311111',
    projectId: 'remouteconfigtest',
    storageBucket: 'remouteconfigtest.appspot.com',
    iosClientId: '930675311111-8vqoo1gl10gisomdfsktndtnq7ilaels.apps.googleusercontent.com',
    iosBundleId: 'com.example.remouteConfigTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1YZR3Q6e35kdUb-jBgviw4ykeFFFDaXA',
    appId: '1:930675311111:ios:890582c6c263e9b726e0a2',
    messagingSenderId: '930675311111',
    projectId: 'remouteconfigtest',
    storageBucket: 'remouteconfigtest.appspot.com',
    iosClientId: '930675311111-lptt1ispkrognm8n8eohkl3ftokddg8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.remouteConfigTest.RunnerTests',
  );
}
